//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czas_pracy
    {
        public int ID_czas_pracy { get; set; }
        public System.DateTime Data { get; set; }
        public int Liczba_godzin { get; set; }
    }
}
