//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czesc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Czesc()
        {
            this.Parametr_czesc = new HashSet<Parametr_czesc>();
            this.Sklad_maszyna = new HashSet<Sklad_maszyna>();
            this.Szczegoly_zamowienie_czesc = new HashSet<Szczegoly_zamowienie_czesc>();
            this.Wymiana_czesc = new HashSet<Wymiana_czesc>();
        }
    
        public int ID_czesc { get; set; }
        public string Nazwa_czesc { get; set; }
        public int ID_rodzaj_czesc { get; set; }
    
        public virtual Rodzaj_czesc Rodzaj_czesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_czesc> Parametr_czesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_maszyna> Sklad_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zamowienie_czesc> Szczegoly_zamowienie_czesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wymiana_czesc> Wymiana_czesc { get; set; }
    }
}
