//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane_adresowe_klient
    {
        public int ID_dane_adresowe_klient { get; set; }
        public int ID_klient { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public int Nr_budynek { get; set; }
        public Nullable<int> Nr_lokal { get; set; }
        public string Kod_pocztowy { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
