//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane_adresowe_pracownik
    {
        public int ID_dane_adresowe_pracownik { get; set; }
        public int ID_pracownik { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string Nr_budynku { get; set; }
        public string Nr_lokalu { get; set; }
        public string Kod_pocztowy { get; set; }
        public System.DateTime Data_od { get; set; }
        public Nullable<System.DateTime> Data_do { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
    }
}
