//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola_parametr
    {
        public int ID_kontrola_parametr { get; set; }
        public int ID_kontrola_jakosci_produkt { get; set; }
        public int ID_parametr_produkt { get; set; }
        public decimal Wartosc { get; set; }
    
        public virtual Kontrola_jakosci_produkt Kontrola_jakosci_produkt { get; set; }
        public virtual Parametr_produkt Parametr_produkt { get; set; }
    }
}
