//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola_jakosci_produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrola_jakosci_produkt()
        {
            this.Kontrola_parametr = new HashSet<Kontrola_parametr>();
        }
    
        public int ID_kontrola_jakosci_produkt { get; set; }
        public int ID_wytwarzanie { get; set; }
        public int ID_pracownik { get; set; }
        public int ID_rodzaj_kontrola { get; set; }
        public System.DateTime Data_od { get; set; }
        public Nullable<System.DateTime> Data_do { get; set; }
        public string Uwagi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_parametr> Kontrola_parametr { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Rodzaj_kontrola Rodzaj_kontrola { get; set; }
        public virtual Wytwarzanie Wytwarzanie { get; set; }
    }
}
