//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maszyna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maszyna()
        {
            this.Maszyna_nr_seryjny = new HashSet<Maszyna_nr_seryjny>();
            this.Parametr_maszyna = new HashSet<Parametr_maszyna>();
            this.Sklad_maszyna = new HashSet<Sklad_maszyna>();
            this.Szczegoly_zamowienie_maszyna = new HashSet<Szczegoly_zamowienie_maszyna>();
        }
    
        public int ID_maszyna { get; set; }
        public string Nazwa_maszyna { get; set; }
        public int ID_rodzaj_maszyna { get; set; }
        public decimal Koszt_RBG { get; set; }
    
        public virtual Rodzaj_maszyna Rodzaj_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maszyna_nr_seryjny> Maszyna_nr_seryjny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_maszyna> Parametr_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_maszyna> Sklad_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zamowienie_maszyna> Szczegoly_zamowienie_maszyna { get; set; }
    }
}
