//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Parametr_material = new HashSet<Parametr_material>();
            this.Sklad_polprodukt = new HashSet<Sklad_polprodukt>();
            this.Sklad_produkt_material = new HashSet<Sklad_produkt_material>();
            this.Szczegoly_zamowienie_material = new HashSet<Szczegoly_zamowienie_material>();
        }
    
        public int ID_material { get; set; }
        public int ID_rodzaj_material { get; set; }
        public string Nazwa_material { get; set; }
    
        public virtual Rodzaj_material Rodzaj_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_material> Parametr_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_polprodukt> Sklad_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_produkt_material> Sklad_produkt_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zamowienie_material> Szczegoly_zamowienie_material { get; set; }
    }
}
