//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KWZPEntities : DbContext
    {
        public KWZPEntities()
            : base("name=KWZPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<Czesc> Czescs { get; set; }
        public virtual DbSet<Czynnosc_produkcyjna> Czynnosc_produkcyjna { get; set; }
        public virtual DbSet<Dane_adresowe_dostawca> Dane_adresowe_dostawca { get; set; }
        public virtual DbSet<Dane_adresowe_klient> Dane_adresowe_klient { get; set; }
        public virtual DbSet<Dane_adresowe_pracownik> Dane_adresowe_pracownik { get; set; }
        public virtual DbSet<Dane_adresowe_producent> Dane_adresowe_producent { get; set; }
        public virtual DbSet<Dostawca> Dostawcas { get; set; }
        public virtual DbSet<Dzial> Dzials { get; set; }
        public virtual DbSet<Email_klient> Email_klient { get; set; }
        public virtual DbSet<Email_pracownik> Email_pracownik { get; set; }
        public virtual DbSet<Etat> Etats { get; set; }
        public virtual DbSet<Forma_platnosc> Forma_platnosc { get; set; }
        public virtual DbSet<Gwarancja> Gwarancjas { get; set; }
        public virtual DbSet<Jednostka> Jednostkas { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Kontrola_jakosci_produkt> Kontrola_jakosci_produkt { get; set; }
        public virtual DbSet<Maszyna> Maszynas { get; set; }
        public virtual DbSet<Maszyna_nr_seryjny> Maszyna_nr_seryjny { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Narzedzie> Narzedzies { get; set; }
        public virtual DbSet<Nieobecnosc> Nieobecnoscs { get; set; }
        public virtual DbSet<Nr_seryjny> Nr_seryjny { get; set; }
        public virtual DbSet<Nr_telefon_klient> Nr_telefon_klient { get; set; }
        public virtual DbSet<Nr_telefon_pracownik> Nr_telefon_pracownik { get; set; }
        public virtual DbSet<Obsluga> Obslugas { get; set; }
        public virtual DbSet<Oferta_handlowa> Oferta_handlowa { get; set; }
        public virtual DbSet<Parametr_czesc> Parametr_czesc { get; set; }
        public virtual DbSet<Parametr_maszyna> Parametr_maszyna { get; set; }
        public virtual DbSet<Parametr_material> Parametr_material { get; set; }
        public virtual DbSet<Parametr_narzedzie> Parametr_narzedzie { get; set; }
        public virtual DbSet<Parametr_polprodukt> Parametr_polprodukt { get; set; }
        public virtual DbSet<Parametr_produkt> Parametr_produkt { get; set; }
        public virtual DbSet<Podatek> Podateks { get; set; }
        public virtual DbSet<Posada_pracownika> Posada_pracownika { get; set; }
        public virtual DbSet<Pracownik> Pracowniks { get; set; }
        public virtual DbSet<Proces_polprodukt_czynnosc> Proces_polprodukt_czynnosc { get; set; }
        public virtual DbSet<Proces_produkt_czynnosc> Proces_produkt_czynnosc { get; set; }
        public virtual DbSet<Proces_wytwarzanie_polprodukt> Proces_wytwarzanie_polprodukt { get; set; }
        public virtual DbSet<Proces_wytwarzanie_produkt> Proces_wytwarzanie_produkt { get; set; }
        public virtual DbSet<Producent> Producents { get; set; }
        public virtual DbSet<Produkt> Produkts { get; set; }
        public virtual DbSet<Reklamacja> Reklamacjas { get; set; }
        public virtual DbSet<Rezultat_kontrola> Rezultat_kontrola { get; set; }
        public virtual DbSet<Rodzaj_czesc> Rodzaj_czesc { get; set; }
        public virtual DbSet<Rodzaj_kontrola> Rodzaj_kontrola { get; set; }
        public virtual DbSet<Rodzaj_maszyna> Rodzaj_maszyna { get; set; }
        public virtual DbSet<Rodzaj_material> Rodzaj_material { get; set; }
        public virtual DbSet<Rodzaj_nieobecnosci> Rodzaj_nieobecnosci { get; set; }
        public virtual DbSet<Rodzaj_obsluga> Rodzaj_obsluga { get; set; }
        public virtual DbSet<Rodzaj_parametr> Rodzaj_parametr { get; set; }
        public virtual DbSet<Rodzaj_umowy> Rodzaj_umowy { get; set; }
        public virtual DbSet<Sklad_maszyna> Sklad_maszyna { get; set; }
        public virtual DbSet<Sklad_polprodukt> Sklad_polprodukt { get; set; }
        public virtual DbSet<Sklad_produkt> Sklad_produkt { get; set; }
        public virtual DbSet<Sklad_produkt_material> Sklad_produkt_material { get; set; }
        public virtual DbSet<Sklad_stanowisko_produkcyjne> Sklad_stanowisko_produkcyjne { get; set; }
        public virtual DbSet<Sklad_stanowisko_produkcyjne_maszyna> Sklad_stanowisko_produkcyjne_maszyna { get; set; }
        public virtual DbSet<Slownik_polprodukt> Slownik_polprodukt { get; set; }
        public virtual DbSet<Slownik_stanowisko> Slownik_stanowisko { get; set; }
        public virtual DbSet<Sprzedaz> Sprzedazs { get; set; }
        public virtual DbSet<Stan_realizacji_zamowienie_czesc> Stan_realizacji_zamowienie_czesc { get; set; }
        public virtual DbSet<Stan_realizacji_zamowienie_maszyna> Stan_realizacji_zamowienie_maszyna { get; set; }
        public virtual DbSet<Stan_realizacji_zamowienie_material> Stan_realizacji_zamowienie_material { get; set; }
        public virtual DbSet<Stan_realizacji_zamowienie_narzedzie> Stan_realizacji_zamowienie_narzedzie { get; set; }
        public virtual DbSet<Stanowisko> Stanowiskoes { get; set; }
        public virtual DbSet<Stanowisko_produkcyjne> Stanowisko_produkcyjne { get; set; }
        public virtual DbSet<Status_oferta> Status_oferta { get; set; }
        public virtual DbSet<Status_zamowienie> Status_zamowienie { get; set; }
        public virtual DbSet<Szczegoly_sprzedaz> Szczegoly_sprzedaz { get; set; }
        public virtual DbSet<Szczegoly_zamowienie_czesc> Szczegoly_zamowienie_czesc { get; set; }
        public virtual DbSet<Szczegoly_zamowienie_maszyna> Szczegoly_zamowienie_maszyna { get; set; }
        public virtual DbSet<Szczegoly_zamowienie_material> Szczegoly_zamowienie_material { get; set; }
        public virtual DbSet<Szczegoly_zamowienie_narzedzie> Szczegoly_zamowienie_narzedzie { get; set; }
        public virtual DbSet<Typ_zamowienie> Typ_zamowienie { get; set; }
        public virtual DbSet<Umowa> Umowas { get; set; }
        public virtual DbSet<Umowa_sprzedaz> Umowa_sprzedaz { get; set; }
        public virtual DbSet<Wyksztalcenie> Wyksztalcenies { get; set; }
        public virtual DbSet<Wymiana_czesc> Wymiana_czesc { get; set; }
        public virtual DbSet<Wymiar_pracy> Wymiar_pracy { get; set; }
        public virtual DbSet<Wytwarzanie> Wytwarzanies { get; set; }
        public virtual DbSet<Zamowienie> Zamowienies { get; set; }
        public virtual DbSet<Zamowienie_czesc> Zamowienie_czesc { get; set; }
        public virtual DbSet<Zamowienie_maszyna> Zamowienie_maszyna { get; set; }
        public virtual DbSet<Zamowienie_material> Zamowienie_material { get; set; }
        public virtual DbSet<Zamowienie_narzedzie> Zamowienie_narzedzie { get; set; }
        public virtual DbSet<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
        public virtual DbSet<Zwrot> Zwrots { get; set; }
        public virtual DbSet<v_Czynnosc_produkcyjna> v_Czynnosc_produkcyjna { get; set; }
        public virtual DbSet<v_Dane_adresowe_pracownik> v_Dane_adresowe_pracownik { get; set; }
        public virtual DbSet<v_Email_pracownik> v_Email_pracownik { get; set; }
        public virtual DbSet<v_Etat> v_Etat { get; set; }
        public virtual DbSet<v_Klient> v_Klient { get; set; }
        public virtual DbSet<v_Klient_telefon_aktualny> v_Klient_telefon_aktualny { get; set; }
        public virtual DbSet<v_Klient_telefon_Historia> v_Klient_telefon_Historia { get; set; }
        public virtual DbSet<v_Kontrola_jakosci_produkt> v_Kontrola_jakosci_produkt { get; set; }
        public virtual DbSet<v_Koszt> v_Koszt { get; set; }
        public virtual DbSet<v_Koszt_procesow_polprodukt> v_Koszt_procesow_polprodukt { get; set; }
        public virtual DbSet<v_Koszt_procesow_produkt> v_Koszt_procesow_produkt { get; set; }
        public virtual DbSet<v_Koszt_roboczogodziny_stanowiska> v_Koszt_roboczogodziny_stanowiska { get; set; }
        public virtual DbSet<v_Liczba_zabiegow_wytworczych_polprodukt> v_Liczba_zabiegow_wytworczych_polprodukt { get; set; }
        public virtual DbSet<v_Liczba_zabiegow_wytworczych_produkt> v_Liczba_zabiegow_wytworczych_produkt { get; set; }
        public virtual DbSet<v_Nieobecnosc> v_Nieobecnosc { get; set; }
        public virtual DbSet<v_Nr_telefon_pracownik> v_Nr_telefon_pracownik { get; set; }
        public virtual DbSet<v_Oblugi_w_trakcie> v_Oblugi_w_trakcie { get; set; }
        public virtual DbSet<v_Oblugi_zakonczone> v_Oblugi_zakonczone { get; set; }
        public virtual DbSet<v_Oferta_handlowa> v_Oferta_handlowa { get; set; }
        public virtual DbSet<v_Parametry_czesc> v_Parametry_czesc { get; set; }
        public virtual DbSet<v_Parametry_maszyna> v_Parametry_maszyna { get; set; }
        public virtual DbSet<v_Parametry_material> v_Parametry_material { get; set; }
        public virtual DbSet<v_Parametry_narzedzie> v_Parametry_narzedzie { get; set; }
        public virtual DbSet<v_Parametry_polprodukt> v_Parametry_polprodukt { get; set; }
        public virtual DbSet<v_Parametry_produkt> v_Parametry_produkt { get; set; }
        public virtual DbSet<v_Pracownik> v_Pracownik { get; set; }
        public virtual DbSet<v_Proces_polprodukt_czynnosc> v_Proces_polprodukt_czynnosc { get; set; }
        public virtual DbSet<v_Proces_produkt_czynnosc> v_Proces_produkt_czynnosc { get; set; }
        public virtual DbSet<v_Proces_wytwarzanie_polprodukt> v_Proces_wytwarzanie_polprodukt { get; set; }
        public virtual DbSet<v_Proces_wytwarzanie_produkt> v_Proces_wytwarzanie_produkt { get; set; }
        public virtual DbSet<v_Produkty_na_gwarancji> v_Produkty_na_gwarancji { get; set; }
        public virtual DbSet<v_Reklamacja> v_Reklamacja { get; set; }
        public virtual DbSet<v_Rodzaj_kontrola> v_Rodzaj_kontrola { get; set; }
        public virtual DbSet<v_Sklad_maszyna> v_Sklad_maszyna { get; set; }
        public virtual DbSet<v_Sklad_polprodukt> v_Sklad_polprodukt { get; set; }
        public virtual DbSet<v_Sklad_produkt> v_Sklad_produkt { get; set; }
        public virtual DbSet<v_Sklad_stanowisko_produkcyjne_maszyna> v_Sklad_stanowisko_produkcyjne_maszyna { get; set; }
        public virtual DbSet<v_Sklad_stanowisko_produkcyjne_narzedzie> v_Sklad_stanowisko_produkcyjne_narzedzie { get; set; }
        public virtual DbSet<v_Slownik_stanowisko> v_Slownik_stanowisko { get; set; }
        public virtual DbSet<v_Sprzedaz> v_Sprzedaz { get; set; }
        public virtual DbSet<v_Stanowiska_do_uzycia> v_Stanowiska_do_uzycia { get; set; }
        public virtual DbSet<v_Stanowiska_w_uzyciu> v_Stanowiska_w_uzyciu { get; set; }
        public virtual DbSet<v_Stanowisko_produkcyjne> v_Stanowisko_produkcyjne { get; set; }
        public virtual DbSet<v_Szczegoly_sprzedaz> v_Szczegoly_sprzedaz { get; set; }
        public virtual DbSet<v_Wytwarzanie> v_Wytwarzanie { get; set; }
        public virtual DbSet<v_Zamowienia_czesci_w_trakcie> v_Zamowienia_czesci_w_trakcie { get; set; }
    }
}
