//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta_handlowa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oferta_handlowa()
        {
            this.Umowa_sprzedaz = new HashSet<Umowa_sprzedaz>();
        }
    
        public int ID_oferta_handlowa { get; set; }
        public int ID_zamowienie { get; set; }
        public int ID_pracownik { get; set; }
        public System.DateTime Termin_realizacja { get; set; }
        public int ID_gwarancja { get; set; }
        public int ID_status_oferta { get; set; }
        public Nullable<int> Cena { get; set; }
    
        public virtual Gwarancja Gwarancja { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Status_oferta Status_oferta { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umowa_sprzedaz> Umowa_sprzedaz { get; set; }
    }
}
