//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr_polprodukt
    {
        public int ID_parametr_polprodukt { get; set; }
        public int ID_polprodukt { get; set; }
        public int ID_rodzaj_parametr { get; set; }
        public decimal Zakres_dol { get; set; }
        public decimal Zakres_gora { get; set; }
    
        public virtual Slownik_polprodukt Slownik_polprodukt { get; set; }
        public virtual Rodzaj_parametr Rodzaj_parametr { get; set; }
    }
}
