//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr_produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parametr_produkt()
        {
            this.Szczegoly_produkt = new HashSet<Szczegoly_produkt>();
        }
    
        public int ID_parametr { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Wartosc_gorna { get; set; }
        public int Nominal { get; set; }
        public Nullable<int> Wartosc_dolna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_produkt> Szczegoly_produkt { get; set; }
    }
}
