//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Dane_adresowe_pracownik = new HashSet<Dane_adresowe_pracownik>();
            this.Email_pracownik = new HashSet<Email_pracownik>();
            this.Kontrola_jakosci_produkt = new HashSet<Kontrola_jakosci_produkt>();
            this.Nadgodziny = new HashSet<Nadgodziny>();
            this.Nieobecnosc = new HashSet<Nieobecnosc>();
            this.Nr_telefon_pracownik = new HashSet<Nr_telefon_pracownik>();
            this.Oferta_handlowa = new HashSet<Oferta_handlowa>();
            this.Reklamacja = new HashSet<Reklamacja>();
            this.Stan_realizacji_zamowienie_material = new HashSet<Stan_realizacji_zamowienie_material>();
            this.Stan_realizacji_zamowienie_czesc = new HashSet<Stan_realizacji_zamowienie_czesc>();
            this.Stan_realizacji_zamowienie_maszyna = new HashSet<Stan_realizacji_zamowienie_maszyna>();
            this.Stan_realizacji_zamowienie_narzedzie = new HashSet<Stan_realizacji_zamowienie_narzedzie>();
            this.Umowa = new HashSet<Umowa>();
            this.Wyplata = new HashSet<Wyplata>();
            this.Wytwarzanie = new HashSet<Wytwarzanie>();
            this.Zamowienie = new HashSet<Zamowienie>();
            this.Zamowienie_material = new HashSet<Zamowienie_material>();
            this.Zamowienie_czesc = new HashSet<Zamowienie_czesc>();
            this.Zamowienie_maszyna = new HashSet<Zamowienie_maszyna>();
            this.Zamowienie_narzedzie = new HashSet<Zamowienie_narzedzie>();
            this.Obsluga = new HashSet<Obsluga>();
        }
    
        public int ID_pracownik { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Nr_dowodu { get; set; }
        public long Pesel { get; set; }
        public int ID_wyksztalcenie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dane_adresowe_pracownik> Dane_adresowe_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email_pracownik> Email_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_jakosci_produkt> Kontrola_jakosci_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nadgodziny> Nadgodziny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nieobecnosc> Nieobecnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nr_telefon_pracownik> Nr_telefon_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_handlowa> Oferta_handlowa { get; set; }
        public virtual Wyksztalcenie Wyksztalcenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja> Reklamacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_material> Stan_realizacji_zamowienie_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_czesc> Stan_realizacji_zamowienie_czesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_maszyna> Stan_realizacji_zamowienie_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_narzedzie> Stan_realizacji_zamowienie_narzedzie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umowa> Umowa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyplata> Wyplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wytwarzanie> Wytwarzanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_material> Zamowienie_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_czesc> Zamowienie_czesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_maszyna> Zamowienie_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_narzedzie> Zamowienie_narzedzie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obsluga> Obsluga { get; set; }
    }
}
