//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_produkt_czynnosc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proces_produkt_czynnosc()
        {
            this.Proces_wytwarzanie_produkt = new HashSet<Proces_wytwarzanie_produkt>();
        }
    
        public int ID_proces_produkt { get; set; }
        public int ID_produkt { get; set; }
        public int ID_czynnosc_produkcyjna { get; set; }
        public int Czas_trwania { get; set; }
    
        public virtual Czynnosc_produkcyjna Czynnosc_produkcyjna { get; set; }
        public virtual Produkt Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_wytwarzanie_produkt> Proces_wytwarzanie_produkt { get; set; }
    }
}
