//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_wytwarzanie_produkt
    {
        public int ID_proces_wytwarzanie_produkt { get; set; }
        public int ID_wytwarzanie { get; set; }
        public Nullable<int> ID_proces_produkt { get; set; }
        public int ID_stanowisko_produkcyjne { get; set; }
    
        public virtual Proces_produkt_czynnosc Proces_produkt_czynnosc { get; set; }
        public virtual Stanowisko_produkcyjne Stanowisko_produkcyjne { get; set; }
        public virtual Wytwarzanie Wytwarzanie { get; set; }
    }
}
