//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprzedaz()
        {
            this.Reklamacja = new HashSet<Reklamacja>();
            this.Szczegoly_sprzedaz = new HashSet<Szczegoly_sprzedaz>();
        }
    
        public int ID_sprzedaz { get; set; }
        public int Nr_sprzadaz { get; set; }
        public int ID_oferta_handlowa { get; set; }
        public System.DateTime Data_sprzedazy { get; set; }
        public System.DateTime Termin_zaplaty { get; set; }
        public int ID_forma_platnosci { get; set; }
    
        public virtual Forma_platnosci Forma_platnosci { get; set; }
        public virtual Oferta_handlowa Oferta_handlowa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja> Reklamacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_sprzedaz> Szczegoly_sprzedaz { get; set; }
    }
}
