//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_zamowienie_narzedzie
    {
        public int ID_zamowienie_narzedzie { get; set; }
        public int ID_narzedzie { get; set; }
        public int ID_producent { get; set; }
        public int Sztuk { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Narzedzie Narzedzie { get; set; }
        public virtual Producent Producent { get; set; }
        public virtual Zamowienie_narzedzie Zamowienie_narzedzie { get; set; }
    }
}
