//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_produkt
    {
        public int ID_szczegoly_produkt { get; set; }
        public int ID_produkt { get; set; }
        public int ID_parametr { get; set; }
    
        public virtual Parametr_produkt Parametr_produkt { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
