//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Alerty_ProductionDepartment_nieodczytane
    {
        public int ID_alert { get; set; }
        public int ID_dzial { get; set; }
        public string Nazwa_dzial { get; set; }
        public string Tresc { get; set; }
        public bool Czy_odczytano { get; set; }
    }
}
