//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Dane_adresowe_pracownik
    {
        public int ID { get; set; }
        public string Miejscowość_zamieszkania { get; set; }
        public string Ulica { get; set; }
        public string Nr_budynku { get; set; }
        public string Nr_lokalu { get; set; }
        public string Kod_pocztowy { get; set; }
        public System.DateTime Data_od_ { get; set; }
        public Nullable<System.DateTime> Data_do_ { get; set; }
    }
}
