//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Klient
    {
        public int ID { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string NIP { get; set; }
        public string Miejscowość { get; set; }
        public string Ulica { get; set; }
        public int Numer_budynku { get; set; }
        public Nullable<int> Numer_lokalu { get; set; }
        public string Kod_pocztowy { get; set; }
    }
}
