//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Koszt_godziny_pracy
    {
        public int ID_pracownik { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public int Wynagrodzenie { get; set; }
        public int Liczba_godzin { get; set; }
        public Nullable<int> Koszt_godziny_pracy { get; set; }
        public Nullable<int> Miesiąc { get; set; }
    }
}
