//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Kontrola_jakosci_produkt
    {
        public string Produkt { get; set; }
        public string Rodzaj_kontroli { get; set; }
        public string Osoba_kontrolująca { get; set; }
        public string Wynik_kontroli { get; set; }
        public string Uwagi { get; set; }
    }
}
