//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Koszty_za_material_produkt
    {
        public int ID_zamowienie { get; set; }
        public int ID_produkt { get; set; }
        public int Ilosc { get; set; }
        public int Liczba { get; set; }
        public Nullable<decimal> Średnia_cena_za__g_ { get; set; }
        public Nullable<decimal> Koszty_za_materiały_produktu { get; set; }
    }
}
