//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Koszty_za_material_produkt_suma
    {
        public int ID_zamowienie { get; set; }
        public Nullable<decimal> Suma_kosztów_materiałów_na_produkt { get; set; }
    }
}
