//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Kontrola_parametr_produkt
    {
        public int ID_wytwarzanie { get; set; }
        public int ID_produkt { get; set; }
        public string Produkt { get; set; }
        public string Parametr { get; set; }
        public decimal Wartość { get; set; }
        public decimal Zakres_dolny { get; set; }
        public decimal Zakres_górny { get; set; }
        public int Rezultat_kontroli { get; set; }
        public int ID_zamowienie { get; set; }
    }
}
