//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Koszt
    {
        public string Nazwa_produkt { get; set; }
        public decimal Koszt_produktów { get; set; }
        public string Nazwa { get; set; }
        public int Liczba { get; set; }
        public decimal Koszt_półproduktów { get; set; }
        public Nullable<decimal> SUMA { get; set; }
    }
}
