//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Liczba_zabiegow_wytworczych_polprodukt
    {
        public Nullable<int> Ilosc_zabiegow { get; set; }
        public string Półprodukt { get; set; }
    }
}
