//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Maszyny_numery_porownanie
    {
        public Nullable<int> ID { get; set; }
        public string Nazwa_maszyny { get; set; }
        public Nullable<int> Liczba_sztuk { get; set; }
        public Nullable<int> Ile_przypisano { get; set; }
    }
}
