//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Nadgodziny_miesiac
    {
        public int ID_Pracownik { get; set; }
        public Nullable<int> Miesiąc { get; set; }
        public int Czas { get; set; }
    }
}
