//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_NieobecnoscUW
    {
        public int ID_pracownik { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Rodzaj_nieobecnosci { get; set; }
        public Nullable<int> Ilosc_UW { get; set; }
        public Nullable<int> Miesiac_nieobecnosci { get; set; }
    }
}
