//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Nieobecnosc
    {
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Rodzaj_nieobecności { get; set; }
        public System.DateTime Data_od_ { get; set; }
        public System.DateTime Data_do_ { get; set; }
    }
}
