//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_NieobecnoscCH
    {
        public int ID_pracownikCH { get; set; }
        public string NazwiskoCH { get; set; }
        public string ImięCH { get; set; }
        public string Rodzaj_nieobecnosci { get; set; }
        public Nullable<int> Ilosc_CH { get; set; }
        public Nullable<int> Miesiac_nieobecnosci { get; set; }
    }
}
