//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Nr_seryjny_maszyna
    {
        public int ID_maszyny { get; set; }
        public string Nazwa_maszyny { get; set; }
        public string Numer_seryjny { get; set; }
    }
}
