//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Obslugi_zakonczone_suma
    {
        public int Nr_stanowiska { get; set; }
        public string Obsługa { get; set; }
        public Nullable<int> Ilość { get; set; }
    }
}
