//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Oferta_handlowa_do_rozpatrzenia
    {
        public int Nr_oferty { get; set; }
        public int Nr_zamówienia { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime Termin_realizacji { get; set; }
        public string Opis_gwarancji { get; set; }
        public string Status_oferty_handlowej { get; set; }
        public Nullable<int> Cena { get; set; }
    }
}
