//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Parametry_czesc
    {
        public int ID_czesc { get; set; }
        public int ID_rodzaj_parametr { get; set; }
        public string Nazwa_części { get; set; }
        public string Parametr { get; set; }
        public string Jednostka { get; set; }
        public decimal Zakres___granica_dolna { get; set; }
        public decimal Zakres___granica_górna { get; set; }
    }
}
