//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Parametry_produkt
    {
        public int ID_parametr_produkt { get; set; }
        public int ID_produkt { get; set; }
        public string Produkt { get; set; }
        public string Parametr { get; set; }
        public decimal Wymiar_minimalny { get; set; }
        public decimal Wymiar_maksymalny { get; set; }
        public string Jednostka { get; set; }
    }
}
