//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Parametry_material
    {
        public string Nazwa_material { get; set; }
        public string Nazwa_rodzaj_parametr { get; set; }
        public string Skrot { get; set; }
        public decimal Zakres_dol { get; set; }
        public decimal Zakres_gora { get; set; }
    }
}
