//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Pracownik_dzial
    {
        public int ID_pracownik { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Nazwa_dzial { get; set; }
    }
}
