//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Proces_produkt_czynnosc
    {
        public int ID_Produktu { get; set; }
        public string Produkt { get; set; }
        public string Czynność { get; set; }
        public int ID_proces_produkt { get; set; }
    }
}
