//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Pracownik
    {
        public int ID { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Nr_dowodu { get; set; }
        public long Pesel { get; set; }
        public string Wykształcenie { get; set; }
        public string Numer_telefonu { get; set; }
        public string Email { get; set; }
    }
}
