//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Proces_polprodukt_czynnosc_projekt
    {
        public int ID_Półproduktu { get; set; }
        public string Półprodukt { get; set; }
        public string Czynność { get; set; }
        public int Czas_wytwarzania_h_ { get; set; }
    }
}
