//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sklad_stanowisko_produkcyjne_maszyna
    {
        public int ID { get; set; }
        public int ID_stanowisko_produkcyjne { get; set; }
        public string Nazwa_stanowiska { get; set; }
        public int ID_maszyna { get; set; }
        public string Nr_seryjny { get; set; }
        public string Nazwa_maszyna { get; set; }
        public string Nazwa_rodzaj_maszyna { get; set; }
    }
}
