//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sklad_stanowisko_produkcyjne_narzedzie
    {
        public int ID_Stanowiska { get; set; }
        public string Nazwa_stanowiska { get; set; }
        public string Narzędzie { get; set; }
        public int Liczba { get; set; }
    }
}
