//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz_statystyki
    {
        public int ID_produkt { get; set; }
        public string Nazwa_produkt { get; set; }
        public System.DateTime Data_sprzedaz_koniec { get; set; }
        public string Nazwisko { get; set; }
        public int Kwota_sprzedaz { get; set; }
        public int Ilosc { get; set; }
        public Nullable<int> Całkowity_koszt { get; set; }
    }
}
