//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz
    {
        public int Numer_sprzedaży { get; set; }
        public string Nazwisko_klienta { get; set; }
        public string Imię_klienta { get; set; }
        public string NIP { get; set; }
        public System.DateTime Data_początku_sprzedaży { get; set; }
        public System.DateTime Data_końca_sprzedaży { get; set; }
        public int Umowa { get; set; }
        public Nullable<int> Koszt { get; set; }
    }
}
