//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz_statystyki_zarobek_dnia
    {
        public System.DateTime Data_sprzedaz_koniec { get; set; }
        public Nullable<int> Zarobek_z_dnia { get; set; }
    }
}
