//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedane_zamowienia
    {
        public int Nr_zamówienia { get; set; }
        public int Nr_sprzedaży { get; set; }
        public int Nr_umowy { get; set; }
        public int Nr_produkt { get; set; }
        public string Produkt { get; set; }
        public int Kwota_sprzedaz { get; set; }
        public int Ilosc { get; set; }
    }
}
