//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sumaryczny_czas_wytwarzania_produktu
    {
        public int ID_produkt { get; set; }
        public string Produkt { get; set; }
        public Nullable<int> Czas { get; set; }
    }
}
