//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Szczegol_sprzedaz
    {
        public int ID_szczegoly_sprzedaz { get; set; }
        public int Nr_sprzedaz { get; set; }
        public int ID_produkt { get; set; }
        public string Nazwa_produkt { get; set; }
        public int ID_sprzedaz { get; set; }
        public int Ilosc { get; set; }
        public int ID_podatek { get; set; }
        public int Procent { get; set; }
        public int Kwota_sprzedaz { get; set; }
    }
}
