//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Umowa_do_sprzedaz
    {
        public int Nr_umowy_sprzedaży { get; set; }
        public int Nr_oferty_handlowej { get; set; }
    }
}
