//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Umowa
    {
        public int ID { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Wymiar_pracy { get; set; }
        public string Rodzaj_Umowy { get; set; }
        public string Nazwa_stanowiska { get; set; }
        public int Podstawa_wynagrodzenia { get; set; }
    }
}
