//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Wymiana_czesc
    {
        public int ID_obsluga { get; set; }
        public int ID_maszyna_nr { get; set; }
        public int ID_czesc { get; set; }
        public System.DateTime Data_od { get; set; }
        public Nullable<System.DateTime> Data_do { get; set; }
        public string Nazwa_maszyna { get; set; }
        public string Nr_seryjny { get; set; }
        public string Nazwa_czesc { get; set; }
    }
}
