//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Wyplata
    {
        public int ID_wypłata { get; set; }
        public int ID_Pracownik { get; set; }
        public System.DateTime Data_wyplaty { get; set; }
        public Nullable<int> Miesiac_wyplata { get; set; }
    }
}
