//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Wytworzone_polprodukty_material
    {
        public int ID_produkt { get; set; }
        public int ID_polprodukt { get; set; }
        public int ID_material { get; set; }
        public string Materiał { get; set; }
        public Nullable<int> Zuzyty_material__g_ { get; set; }
    }
}
