//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienia_narzedzia_status_zamowiono_zmiana_daty
    {
        public string Data_miesiac { get; set; }
        public decimal Cena { get; set; }
    }
}
