//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zarobek_sprzedaz_miesiac
    {
        public int ID_zamowienie { get; set; }
        public string Miesiąc { get; set; }
        public Nullable<decimal> Zarobek_z_miesiąca { get; set; }
    }
}
