//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienie
    {
        public System.DateTime Data_przyjęcia { get; set; }
        public int Nr_zamówienia { get; set; }
        public string Nazwisko_klienta { get; set; }
        public string Imię_klienta { get; set; }
        public string Typ_zamówienia { get; set; }
        public string Nazwisko_pracownika { get; set; }
        public string Imię_pracownika { get; set; }
    }
}
