//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienia_materialy_w_trakcie
    {
        public int Nr_zamówienia { get; set; }
        public string Nazwa_materiału { get; set; }
        public System.DateTime Data_zmiany_stanu { get; set; }
        public int Waga__g_ { get; set; }
        public decimal Cena { get; set; }
        public string Status { get; set; }
        public int StatusID { get; set; }
    }
}
