//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wymienione_czesci
    {
        public int ID_wymienione_czesci { get; set; }
        public Nullable<int> ID_czesc { get; set; }
    
        public virtual Czesc Czesc { get; set; }
    }
}
