//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.Oferta_handlowa = new HashSet<Oferta_handlowa>();
            this.Zamowienie_szczegol = new HashSet<Zamowienie_szczegol>();
        }
    
        public int ID_zamowienie { get; set; }
        public int ID_klient { get; set; }
        public int ID_pracownik { get; set; }
        public System.DateTime Data_zamowienie { get; set; }
        public int ID_typ_zamowienie { get; set; }
    
        public virtual Klient Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_handlowa> Oferta_handlowa { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Typ_zamowienie Typ_zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
    }
}
