//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zwrot
    {
        public int ID_zwrot { get; set; }
        public int ID_reklamacja { get; set; }
        public int ID_produkt { get; set; }
        public int Ilosc { get; set; }
        public bool Akceptacja { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Reklamacja Reklamacja { get; set; }
    }
}
